INSERT INTO actors (firstname, lastname, bio, rating) VALUES
('Robert', 'De Niro', 'American actor known for intense portrayals in ''Taxi Driver'' and ''Raging Bull''', 9.3),
('Al', 'Pacino', 'American actor acclaimed for roles in ''The Godfather'', ''Scarface'', and ''Heat''', 9.4),
('Meryl', 'Streep', 'American actress and three-time Oscar winner known for ''Sophie''s Choice'' and ''The Iron Lady''', 9.6),
('Leonardo', 'DiCaprio', 'American actor and producer known for ''Inception'', ''Titanic'', and ''The Revenant''', 9.3),
('Tom', 'Hanks', 'American actor and two-time Oscar winner known for ''Forrest Gump'' and ''Saving Private Ryan''', 9.2),
('Denzel', 'Washington', 'American actor celebrated for performances in ''Training Day'' and ''Malcolm X''', 9.1),
('Cate', 'Blanchett', 'Australian actress and two-time Oscar winner for ''Blue Jasmine'' and ''Elizabeth: The Golden Age''', 8.9),
('Morgan', 'Freeman', 'American actor and Oscar winner known for ''Shawshank Redemption'' and ''Million Dollar Baby''', 9.0),
('Jack', 'Nicholson', 'American actor and three-time Oscar winner known for ''One Flew Over the Cuckoo’s Nest'' and ''As Good as It Gets''', 9.2),
('Natalie', 'Portman', 'Israeli-American actress known for ''Black Swan'' and ''V for Vendetta''', 8.8),
('Brad', 'Pitt', 'American actor and producer known for ''Fight Club'' and ''Once Upon a Time in Hollywood''', 8.7),
('Angelina', 'Jolie', 'American actress and Oscar winner known for ''Girl, Interrupted'' and ''Maleficent''', 8.7),
('Anthony', 'Hopkins', 'Welsh actor and Oscar winner known for ''The Silence of the Lambs'' and ''The Father''', 9.0),
('Joaquin', 'Phoenix', 'American actor and Oscar winner known for ''Joker'' and ''Gladiator''', 8.8),
('Kate', 'Winslet', 'British actress known for ''Titanic'' and ''The Reader''', 8.9),
('Christian', 'Bale', 'British actor known for ''American Psycho'' and ''The Dark Knight''', 8.7),
('Emma', 'Stone', 'American actress and Oscar winner known for ''La La Land'' and ''The Favourite''', 8.6),
('Matthew', 'McConaughey', 'American actor and Oscar winner known for ''Dallas Buyers Club'' and ''Interstellar''', 8.5),
('Jennifer', 'Lawrence', 'American actress known for ''Silver Linings Playbook'' and ''The Hunger Games''', 8.6),
('Hilary', 'Swank', 'American actress and two-time Oscar winner known for ''Boys Don''t Cry'' and ''Million Dollar Baby''', 8.4),
('Chris', 'Hemsworth', 'Australian actor known for playing Thor in the Marvel Cinematic Universe.', 8.3),
('Chris', 'Evans', 'American actor best known for his role as Captain America in the MCU.', 8.2),
('Chris', 'Pratt', 'American actor recognized for roles in "Guardians of the Galaxy" and "Jurassic World".', 8.0),
('Mark', 'Ruffalo', 'American actor acclaimed for "Spotlight" and as Hulk in the MCU.', 8.3),
('Benedict', 'Cumberbatch', 'British actor known for "Sherlock" and "Doctor Strange".', 8.6),
('Tom', 'Holland', 'English actor best known for portraying Spider-Man in the MCU.', 8.0),
('Chadwick', 'Boseman', 'American actor celebrated for "Black Panther" and "42".', 8.7),
('Scarlett', 'Johansson', 'American actress recognized for roles in "Lost in Translation" and the MCU.', 8.5),
('Elizabeth', 'Olsen', 'American actress praised for "WandaVision" and indie film roles.', 8.4),
('Paul', 'Bettany', 'British actor known for "A Beautiful Mind" and as Vision in the MCU.', 8.1),
('Tom', 'Cruise', 'American actor and producer, known for the "Mission: Impossible" series.', 8.2),
('Keanu', 'Reeves', 'Canadian actor famous for "The Matrix", "John Wick", and "Speed".', 8.3),
('Sandra', 'Bullock', 'American actress known for "The Blind Side" and "Gravity".', 8.2),
('Anne', 'Hathaway', 'American actress known for "Les Misérables" and "The Devil Wears Prada".', 8.1),
('Amy', 'Adams', 'American actress praised for "Arrival", "American Hustle", and "Enchanted".', 8.4),
('Jessica', 'Chastain', 'American actress known for "Zero Dark Thirty" and "The Eyes of Tammy Faye".', 8.4),
('Emily', 'Blunt', 'British-American actress known for "A Quiet Place" and "Edge of Tomorrow".', 8.2),
('Ryan', 'Gosling', 'Canadian actor known for "La La Land", "Drive", and "Barbie".', 8.3),
('Rachel', 'McAdams', 'Canadian actress recognized for "The Notebook" and "Spotlight".', 8.1),
('Hugh', 'Jackman', 'Australian actor known for "Logan", "Les Misérables", and "The Greatest Showman".', 8.4),
('Patrick', 'Stewart', 'British actor renowned for his role as Professor X and Captain Picard.', 8.4),
('Ian', 'McKellen', 'English actor known for portraying Gandalf and Magneto.', 8.5),
('Michael', 'Fassbender', 'Irish-German actor praised for "12 Years a Slave" and "Steve Jobs".', 8.3),
('James', 'McAvoy', 'Scottish actor recognized for "Split", "Atonement", and the X-Men series.', 8.2),
('Zoe', 'Saldana', 'American actress known for "Avatar", "Guardians of the Galaxy", and "Star Trek".', 8.1),
('Jake', 'Gyllenhaal', 'American actor acclaimed for "Nightcrawler", "Brokeback Mountain", and "Prisoners".', 8.4),
('Heath', 'Ledger', 'Australian actor remembered for his role as the Joker in "The Dark Knight".', 9.0),
('Robin', 'Williams', 'Legendary comedian and actor known for "Dead Poets Society", "Good Will Hunting", and "Mrs. Doubtfire".', 9.0),
('Jim', 'Carrey', 'Comedic actor known for "The Truman Show", "Eternal Sunshine", and "The Mask".', 8.2),
('Will', 'Smith', 'American actor and rapper recognized for "The Pursuit of Happyness" and "Men in Black".', 8.3),
('Ben', 'Affleck', 'American actor and filmmaker known for "Argo", "Gone Girl", and as Batman.', 8.0),
('Matt', 'Damon', 'American actor recognized for "Good Will Hunting", "The Martian", and the Bourne series.', 8.3),
('Morgan', 'Freeman', 'Veteran actor known for "The Shawshank Redemption", "Se7en", and narrating roles.', 9.0),
('Liam', 'Neeson', 'Irish actor famous for "Schindler’s List", "Taken", and "Batman Begins".', 8.2),
('Nicole', 'Kidman', 'Australian actress recognized for "Moulin Rouge!", "The Hours", and "Big Little Lies".', 8.3),
('Reese', 'Witherspoon', 'American actress known for "Legally Blonde", "Walk the Line", and "Wild".', 8.1),
('Viola', 'Davis', 'American actress acclaimed for "Fences", "The Help", and "How to Get Away with Murder".', 8.6),
('Octavia', 'Spencer', 'American actress praised for "The Help", "Hidden Figures", and "Ma".', 8.2),
('Mahershala', 'Ali', 'American actor who won Oscars for "Moonlight" and "Green Book".', 8.6),
('Jared', 'Leto', 'Actor and musician known for "Dallas Buyers Club", "Requiem for a Dream", and as the Joker.', 7.9),
('Bryan', 'Cranston', 'American actor acclaimed for his role as Walter White in "Breaking Bad".', 8.8),
('Aaron', 'Paul', 'American actor best known for playing Jesse Pinkman in "Breaking Bad".', 8.3),
('Anna', 'Kendrick', 'American actress known for "Pitch Perfect", "Up in the Air", and "Into the Woods".', 7.8),
('Chris', 'Pratt', 'American actor famous for "Guardians of the Galaxy", "Jurassic World", and "Parks and Recreation".', 8.0),
('Elizabeth', 'Olsen', 'American actress known for her role as Wanda in the Marvel Cinematic Universe.', 8.3),
('Sebastian', 'Stan', 'Romanian-American actor recognized for his role as Bucky Barnes / Winter Soldier.', 8.1),
('Florence', 'Pugh', 'English actress acclaimed for "Midsommar", "Little Women", and "Don’t Worry Darling".', 8.4),
('Tilda', 'Swinton', 'British actress known for "We Need to Talk About Kevin", "Doctor Strange", and "Snowpiercer".', 8.2),
('Willem', 'Dafoe', 'Veteran actor acclaimed for roles in "The Lighthouse", "Spider-Man", and "Platoon".', 8.6),
('Edward', 'Norton', 'American actor known for "Fight Club", "American History X", and "Primal Fear".', 8.7),
('Rachel', 'McAdams', 'Canadian actress recognized for "The Notebook", "Spotlight", and "Mean Girls".', 8.1),
('Amy', 'Adams', 'American actress acclaimed for "Arrival", "Enchanted", and "American Hustle".', 8.5),
('Jessica', 'Chastain', 'Award-winning actress known for "Zero Dark Thirty", "The Help", and "Molly’s Game".', 8.4),
('Rami', 'Malek', 'American actor who portrayed Freddie Mercury in "Bohemian Rhapsody".', 8.3),
('Daniel', 'Craig', 'British actor best known as James Bond in the 007 series.', 8.4),
('Naomi', 'Watts', 'British actress known for "The Impossible", "Mulholland Drive", and "King Kong".', 8.2),
('Ethan', 'Hawke', 'Actor and writer known for "Before Sunrise", "Training Day", and "Boyhood".', 8.3),
('Julie', 'Delpy', 'French-American actress and filmmaker known for the "Before" trilogy.', 7.9),
('Cillian', 'Murphy', 'Irish actor recognized for "Peaky Blinders", "Oppenheimer", and "28 Days Later".', 8.7),
('Emily', 'Blunt', 'British actress known for "A Quiet Place", "Edge of Tomorrow", and "Mary Poppins Returns".', 8.4),
('Oscar', 'Isaac', 'Guatemalan-American actor known for "Ex Machina", "Inside Llewyn Davis", and "Dune".', 8.3),
('Pedro', 'Pascal', 'Chilean-American actor known for "The Mandalorian", "The Last of Us", and "Narcos".', 8.5),
('Millie', 'Bobby Brown', 'British actress known for her role as Eleven in "Stranger Things".', 8.1),
('David', 'Harbour', 'American actor known for "Stranger Things" and "Hellboy".', 7.9),
('Winona', 'Ryder', 'American actress famous for "Beetlejuice", "Heathers", and "Stranger Things".', 8.0),
('Rami', 'Malek', 'Oscar-winning actor known for "Bohemian Rhapsody", "Mr. Robot", and "No Time to Die".', 8.4),
('Toni', 'Collette', 'Australian actress known for "Hereditary", "The Sixth Sense", and "Little Miss Sunshine".', 8.5),
('Emily', 'Blunt', 'British actress known for "A Quiet Place", "Sicario", and "The Devil Wears Prada".', 8.3),
('Daniel', 'Radcliffe', 'British actor best known for playing Harry Potter in the film series.', 8.2),
('Rupert', 'Grint', 'English actor known for playing Ron Weasley in the "Harry Potter" films.', 7.9),
('Emma', 'Watson', 'English actress known for "Harry Potter", "Beauty and the Beast", and activism.', 8.4),
('Tom', 'Felton', 'British actor known for portraying Draco Malfoy in the "Harry Potter" series.', 7.8),
('Domhnall', 'Gleeson', 'Irish actor known for roles in "Ex Machina", "About Time", and "Star Wars".', 8.0),
('Oscar', 'Isaac', 'American actor known for "Dune", "Ex Machina", and "Moon Knight".', 8.3),
('Pedro', 'Pascal', 'Chilean-American actor known for "The Mandalorian", "The Last of Us", and "Game of Thrones".', 8.6),
('Mads', 'Mikkelsen', 'Danish actor known for "Hannibal", "Another Round", and "Casino Royale".', 8.4),
('Timothée', 'Chalamet', 'American actor known for "Dune", "Call Me by Your Name", and "Wonka".', 8.3),
('Anya', 'Taylor-Joy', 'Argentine-British actress known for "The Queen’s Gambit", "The Menu", and "Last Night in Soho".', 8.5),
('Millie', 'Bobby Brown', 'British actress known for playing Eleven in "Stranger Things".', 8.1),
('Aaron', 'Paul', 'American actor best known for playing Jesse Pinkman in "Breaking Bad".', 8.3)




