INSERT INTO movies (title, year, description, rating) VALUES
('The Shawshank Redemption', 1994, 'Two imprisoned men bond over years, finding solace and redemption through acts of common decency.', 9.3),
('The Godfather', 1972, 'The aging patriarch of an organized crime dynasty transfers control of his empire to his reluctant son.', 9.2),
('The Dark Knight', 2008, 'Batman battles the Joker, who seeks to undermine his influence and create chaos in Gotham City.', 9.0),
('Pulp Fiction', 1994, 'The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in tales of violence and redemption.', 8.9),
('Forrest Gump', 1994, 'The story of Forrest, a man with a low IQ, who inadvertently influences many major historical events.', 8.8),
('Inception', 2010, 'A thief who steals corporate secrets through dream-sharing technology is given an inverse task of planting an idea.', 8.7),
('Fight Club', 1999, 'An insomniac office worker and a devil-may-care soap maker form an underground fight club.', 8.8),
('The Matrix', 1999, 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war.', 8.7),
('Se7en', 1995, 'Two detectives hunt a serial killer who uses the seven deadly sins as his motives.', 8.6),
('The Silence of the Lambs', 1991, 'A young FBI cadet must confide in an incarcerated and manipulative killer to catch another serial killer.', 8.6),
('WALL·E', 2008, 'In the distant future, a small waste-collecting robot inadvertently embarks on a space journey.', 8.4),
('The Lives of Others', 2006, 'In 1984 East Berlin, a secret police agent becomes absorbed in the lives of the people he’s spying on.', 8.4),
('Oldboy', 2003, 'After being kidnapped and imprisoned for 15 years, a man is released and must find his captor.', 8.4),
('Avengers: Endgame', 2019, 'The Avengers assemble once more to reverse Thanos’ actions and restore balance to the universe.', 8.4),
('Django Unchained', 2012, 'With the help of a German bounty-hunter, a freed slave sets out to rescue his wife.', 8.4),
('Spider-Man: No Way Home', 2021, 'Peter Parker’s identity is revealed, leading to multiverse-shattering consequences.', 8.3),
('Braveheart', 1995, 'Scottish warrior William Wallace leads his countrymen in a rebellion against the English.', 8.3),
('The Prestige', 2006, 'After a tragic accident, two stage magicians engage in a battle to create the ultimate illusion.', 8.5),
('Alien', 1979, 'The crew of a commercial spacecraft encounters a deadly lifeform after investigating a distress signal.', 8.5),
('Memento', 2000, 'A man with short-term memory loss attempts to track down his wife’s murderer.', 8.4),
('The Departed', 2006, 'An undercover cop and a mole in the police try to identify each other while infiltrating an Irish gang in Boston.', 8.5),
('The Lion King', 1994, 'Lion prince Simba flees his kingdom after the death of his father, only to learn the true meaning of responsibility and bravery.', 8.5),
('The Shining', 1980, 'A family heads to an isolated hotel for the winter where a sinister presence influences the father into violence.', 8.4),
('Whiplash', 2014, 'A young drummer enrolls in a cutthroat music conservatory where his dreams are mentored by an abusive instructor.', 8.5),
('The Wolf of Wall Street', 2013, 'Based on the true story of Jordan Belfort, from his rise to a wealthy stockbroker to his fall involving crime and corruption.', 8.2),
('A Beautiful Mind', 2001, 'After John Nash, a brilliant but asocial mathematician, accepts secret work in cryptography, his life takes a turn for the nightmarish.', 8.2),
('Room', 2015, 'Held captive for years in an enclosed space, a woman and her young son finally gain their freedom.', 8.1),
('Her', 2013, 'In a near future, a lonely writer develops an unlikely relationship with an operating system designed to meet his every need.', 8.0),
('The Grand Budapest Hotel', 2014, 'A hotel concierge teams up with one of his employees to prove his innocence after he is framed for murder.', 8.1),
('The Social Network', 2010, 'The story of Facebook’s founding and the legal battles that followed its meteoric rise.', 7.7),
('Black Swan', 2010, 'A committed dancer struggles to maintain her sanity after winning the lead role in a production of Swan Lake.', 8.0),
('The Revenant', 2015, 'A frontiersman on a fur trading expedition in the 1820s fights for survival after being mauled by a bear.', 8.0),
('Blade Runner 2049', 2017, 'A young blade runner discovers a long-buried secret that leads him to track down former blade runner Rick Deckard.', 8.0),
('La La Land', 2016, 'While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations.', 8.0),
('Moonlight', 2016, 'A young African-American man grapples with his identity and sexuality while growing up in a rough neighborhood of Miami.', 7.4),
('Mad Max: Fury Road', 2015, 'In a post-apocalyptic wasteland, Max helps a rebellious woman flee from a tyrant.', 8.1),
('Arrival', 2016, 'A linguist works with the military to communicate with alien lifeforms after twelve mysterious spacecraft appear around the world.', 7.9),
('The Hateful Eight', 2015, 'In the dead of a Wyoming winter, bounty hunters try to find shelter during a blizzard but get involved in a plot of betrayal and deception.', 7.8),
('Birdman', 2014, 'A washed-up superhero actor attempts to revive his fading career by writing, directing, and starring in a Broadway production.', 7.7),
('Manchester by the Sea', 2016, 'A man is forced to deal with his painful past after he becomes the guardian of his teenage nephew.', 7.8),
('Inside Out', 2015, 'After young Riley is uprooted from her Midwest life, her emotions conflict on how best to navigate a new city.', 8.1),
('Coco', 2017, 'Aspiring musician Miguel enters the Land of the Dead to find his great-great-grandfather, a legendary singer.', 8.4),
('Jojo Rabbit', 2019, 'A young boy in Hitler’s army finds out his mother is hiding a Jewish girl in their home.', 7.9),
('Parasite', 2019, 'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.', 8.5),
('Ford v Ferrari', 2019, 'American car designer Carroll Shelby and driver Ken Miles build a revolutionary race car for Ford to defeat Ferrari at Le Mans.', 8.1),
('1917', 2019, 'Two British soldiers are sent to deliver a message to prevent 1,600 men from walking into a deadly trap.', 8.2),
('Joker', 2019, 'In Gotham City, a mentally troubled comedian embarks on a downward spiral of social revolution and bloody crime.', 8.4),
('Tenet', 2020, 'Armed with only one word, a protagonist journeys through a twilight world of international espionage on a mission that will unfold in something beyond real time.', 7.3),
('The Trial of the Chicago 7', 2020, 'The story of seven people on trial stemming from various charges surrounding the uprising at the 1968 Democratic National Convention in Chicago.', 7.8),
('Soul', 2020, 'A musician who has lost his passion for music is transported out of his body and must find his way back with the help of an infant soul.', 8.0),
('Sound of Metal', 2019, 'A heavy-metal drummer’s life is thrown into freefall when he begins to lose his hearing.', 7.8),
('Promising Young Woman', 2020, 'A young woman, traumatized by a tragic event in her past, seeks out vengeance against those who cross her path.', 7.5),
('Nomadland', 2020, 'A woman in her sixties who, after losing everything in the Great Recession, embarks on a journey through the American West.', 7.4),
('The Father', 2020, 'A man refuses all assistance from his daughter as he ages and begins to doubt his loved ones, his mind, and even the fabric of his reality.', 8.3),
('Minari', 2020, 'A Korean-American family moves to an Arkansas farm in search of their own American Dream.', 7.5),
('The French Dispatch', 2021, 'A love letter to journalists, set in an outpost of an American newspaper in a fictional 20th-century French city.', 7.1),
('Dune', 2021, 'A noble family becomes embroiled in a war for control over the galaxy’s most valuable asset while its heir becomes troubled by visions of a dark future.', 8.0),
('The Power of the Dog', 2021, 'A charismatic rancher inspires fear and awe in those around him, but secrets lurk beneath the surface.', 6.8),
('Don’t Look Up', 2021, 'Two astronomers must go on a media tour to warn mankind of an approaching comet that will destroy Earth.', 7.2),
('King Richard', 2021, 'A look at how tennis superstars Venus and Serena Williams became who they are after the coaching from their father Richard Williams.', 7.5),
('West Side Story', 2021, 'An adaptation of the 1957 musical explores forbidden love and the rivalry between the Jets and the Sharks, two teenage street gangs.', 7.2),
('Everything Everywhere All At Once', 2022, 'An aging Chinese immigrant is swept up in an insane adventure across the multiverse.', 8.7),
('The Batman', 2022, 'When a sadistic killer leaves behind a trail of cryptic clues, Batman must investigate the city’s hidden corruption.', 7.8),
('Top Gun: Maverick', 2022, 'After more than thirty years of service, Maverick is still pushing the envelope as a top naval aviator.', 8.2),
('The Whale', 2022, 'A reclusive English teacher living with severe obesity attempts to reconnect with his estranged teenage daughter.', 7.7),
('Barbie', 2023, 'Barbie suffers a crisis that leads her to question her world and her existence.', 7.0),
('Killers of the Flower Moon', 2023, 'Members of the Osage tribe in the U.S. are murdered under mysterious circumstances in the 1920s, sparking a major FBI investigation.', 7.8),
('The Marvels', 2023, 'Carol Danvers, Monica Rambeau, and Kamala Khan team up to face a new cosmic threat.', 6.0),
('Napoleon', 2023, 'A look at the military commander’s rise to power and his relationship with Empress Joséphine.', 6.7),
('The Holdovers', 2023, 'A cranky history teacher is forced to remain on campus during Christmas break and bond with a troubled student.', 8.0),
('Wonka', 2023, 'The story of how a young Willy Wonka met the Oompa-Loompas and became a famous chocolate maker.', 7.5),
('The Hunger Games: The Ballad of Songbirds & Snakes', 2023, 'Coriolanus Snow mentors and develops feelings for the female District 12 tribute during the 10th Hunger Games.', 7.1),
('Past Lives', 2023, 'Nora and Hae Sung, two deeply connected childhood friends, are wrest apart and reunite years later.', 7.9),
('Maestro', 2023, 'The complex love story of Leonard Bernstein and Felicia Montealegre Cohn Bernstein.', 6.9),
('Poor Things', 2023, 'The fantastical evolution of a young woman brought back to life by an unorthodox scientist.', 8.3),
('Saltburn', 2023, 'A student is invited to an eccentric aristocrat’s country estate for the summer, revealing secrets and temptations.', 7.2),
('Ferrari', 2023, 'The story of Enzo Ferrari’s life and his battles on and off the racetrack.', 6.8),
('The Iron Claw', 2023, 'The tragic true story of the Von Erich brothers, a dynasty of professional wrestlers in the 1980s.', 8.0),
('Society of the Snow', 2023, 'Survivors of a plane crash in the Andes in 1972 must resort to extreme measures to stay alive.', 7.9),
('Migration', 2023, 'A family of ducks decides to leave the pond and go on a trip of a lifetime.', 6.5),
('The Creator', 2023, 'In a future war between humans and AI, a former soldier finds a robot child with the power to end the conflict.', 7.0),
('Wish', 2023, 'A young girl wishes upon a star and meets a mischievous star with magical powers.', 5.9),
('The Killer', 2023, 'An assassin battles his employers, and himself, on an international manhunt he insists isn’t personal.', 6.9),
('Leave the World Behind', 2023, 'A family vacation turns sinister when a cyberattack knocks out communications.', 6.5),
('Spider-Man: Across the Spider-Verse', 2023, 'Miles Morales goes on an adventure across the multiverse with Gwen Stacy and other Spider-People.', 8.6),
('Oppenheimer', 2023, 'The story of J. Robert Oppenheimer and the creation of the atomic bomb.', 8.5),
('Elemental', 2023, 'In a city where fire, water, land and air residents live together, a fiery young woman and a go-with-the-flow guy discover something elemental: how much they have in common.', 7.0),
('No Hard Feelings', 2023, 'On the brink of losing her childhood home, Maddie finds an intriguing job listing: wealthy helicopter parents looking for someone to date their introverted 19-year-old son.', 6.4),
('Asteroid City', 2023, 'A fictional American desert town hosts a Junior Stargazer convention that is spectacularly disrupted by world-changing events.', 6.7),
('Indiana Jones and the Dial of Destiny', 2023, 'Archaeologist Indiana Jones races against time to retrieve a legendary artifact that can change the course of history.', 6.7),
('John Wick: Chapter 4', 2023, 'John Wick uncovers a path to defeating the High Table. But before he can earn his freedom, Wick must face off against a new enemy.', 7.7),
('The Flash', 2023, 'Barry Allen uses his super speed to change the past, but his attempt to save his family creates a world without superheroes.', 6.8),
('Guardians of the Galaxy Vol. 3', 2023, 'The Guardians rally to defend the universe and protect one of their own.', 8.1),
('Mission: Impossible – Dead Reckoning Part One', 2023, 'Ethan Hunt and his IMF team must track down a terrifying new weapon that threatens all of humanity.', 7.8),
('The Super Mario Bros. Movie', 2023, 'A plumber named Mario travels through an underground labyrinth with his brother, Luigi, to save a captured princess.', 7.1),
('Indiana Jones and the Dial of Destiny', 2023, 'Archaeologist Indiana Jones races against time to retrieve a legendary artifact that can change the course of history.', 6.7),
('Guardians of the Galaxy Vol. 3', 2023, 'The Guardians rally to defend the universe and protect one of their own.', 8.1),
('Oppenheimer', 2023, 'The story of J. Robert Oppenheimer and the creation of the atomic bomb.', 8.5),
('Leave the World Behind', 2023, 'A family vacation turns sinister when a cyberattack knocks out communications.', 6.5),
('The Batman', 2022, 'When a sadistic killer leaves behind a trail of cryptic clues, Batman must investigate the city’s hidden corruption.', 7.8)